performance:
    max-number-of-workers: 8

server:
    addr: 0.0.0.0
    port: 8082

network:
    db:
        user: postgres
        password: postgres
        host: db
        port: 5432
        database-name: postgres

timeout:
    read: 7
    write: 7
    idle: 7
    wait: 7